spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.200:3306/zhiliao_ums
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.100:8848
  application:
    name: zhiliao-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*:xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000